### ISSUE TITLE
Missing VTIMEZONE

### ISSUE THREAD

**Issue by varac** [pimutils/todoman#263]
I was debugging [events created by todoman for which davdroid failed to sync](https://forums.bitfire.at/topic/1524/java-lang-noclassdeffounderror-org-threeten-bp-zone-zonerulesprovider).

[rfc2822 found out that one part of the issue was that todoman didn't include a `VTIMEZONE` for each `TZID` in caldav](https://forums.bitfire.at/topic/1524/java-lang-noclassdeffounderror-org-threeten-bp-zone-zonerulesprovider/15):

```
Seems that todoman uses TZID without specifying its VTIMEZONE, which is not allowed in CalDAV (there MUST be a VTIMEZONE for each TZID). Can you please report that to todoman and maybe provide a reference link here?
```

Please implement this in order to make the combination of todoman/vdirsyncer/davdroid more robust.

**Comment by geier** [comment]
This is probably a good time to clean up khal's VTIMEZONE creation code and trying to get it into icalendar.

**Comment by hobarrera** [comment]
So there's three ways around this:

1. Save the VTIMEZONEs (duh).
2. Wait for `icalendar` to implement this.
3. Always save in UTC (seems the simplest, and cleanest way to deal with this).

@geier Do you think you'll have time to look at this on `icalendar`'s side soon? If so, I can wait for that.

**Comment by geier** [comment]
probably not :( 

Quoting Hugo Osvaldo Barrera (2017-08-24 18:31:24)

**Comment by hobarrera** [comment]
@varac: Can you confirm that `compensate-lack-of-vtimezone`/#272 fixes the issue for you? You'll need to open and save any affected todos for them to be updated (or create a new one if you're just testing).

**Comment by varac** [comment]
> Can you confirm that compensate-lack-of-vtimezone/#272 fixes the issue for you? 

I installed todoman via pipsi, so a release containing this fix would be awesome, then I'll give feedback.

**Comment by hobarrera** [comment]
I've pushed v3.2.2, and it should appear on PyPI soon.

**Comment by varac** [comment]
@hobarrera  https://pypi.python.org/pypi/todoman still shows 3.2.1 as latest version.

**Comment by hobarrera** [comment]
I changed how pushing is done yesterday, and 3.2.4 is now out.

**Comment by varac** [comment]
@hobarrera I upgraded todoman to 3.2.4, created a new task but the `VTIMEZONE` is still missing:

```
--- ~ » pipsi upgrade todoman
Collecting todoman
  Downloading todoman-3.2.4-py3-none-any.whl
Requirement already up-to-date: atomicwrites in ./.local/venvs/todoman/lib/python3.5/site-packages (from todoman)
Requirement already up-to-date: configobj in ./.local/venvs/todoman/lib/python3.5/site-packages (from todoman)
Requirement already up-to-date: icalendar in ./.local/venvs/todoman/lib/python3.5/site-packages (from todoman)
Requirement already up-to-date: tabulate in ./.local/venvs/todoman/lib/python3.5/site-packages (from todoman)
Requirement already up-to-date: pyxdg in ./.local/venvs/todoman/lib/python3.5/site-packages (from todoman)
Requirement already up-to-date: click>=6.0 in ./.local/venvs/todoman/lib/python3.5/site-packages (from todoman)
Requirement already up-to-date: urwid in ./.local/venvs/todoman/lib/python3.5/site-packages (from todoman)
Requirement already up-to-date: parsedatetime in ./.local/venvs/todoman/lib/python3.5/site-packages (from todoman)
Requirement already up-to-date: humanize in ./.local/venvs/todoman/lib/python3.5/site-packages (from todoman)
Requirement already up-to-date: python-dateutil in ./.local/venvs/todoman/lib/python3.5/site-packages (from todoman)
Requirement already up-to-date: six in ./.local/venvs/todoman/lib/python3.5/site-packages (from configobj->todoman)
Requirement already up-to-date: pytz in ./.local/venvs/todoman/lib/python3.5/site-packages (from icalendar->todoman)
Requirement already up-to-date: future in ./.local/venvs/todoman/lib/python3.5/site-packages (from parsedatetime->todoman)
Installing collected packages: todoman
  Found existing installation: todoman 3.2.1
    Uninstalling todoman-3.2.1:
      Successfully uninstalled todoman-3.2.1
Successfully installed todoman-3.2.4
--- ~ » todo --version                                                                                                                                                                                        
todoman, version 3.2.4

--- ~ » todo new     
89  [ ]    in 23 hours  test @personal

--- calendars/personal » cat 8d153e0026464b93832f25f0844f1674@laptop.ics
BEGIN:VCALENDAR
VERSION:2.0
PRODID:io.barrera.todoman
BEGIN:VTODO
CREATED;VALUE=DATE-TIME:20170912T131517Z
DTSTAMP;VALUE=DATE-TIME:20170912T131517Z
DUE;VALUE=DATE-TIME:20170913T131517Z
LAST-MODIFIED;VALUE=DATE-TIME:20170912T131523Z
SEQUENCE:1
STATUS:NEEDS-ACTION
SUMMARY:test
UID:8d153e0026464b93832f25f0844f1674@laptop
END:VTODO
END:VCALENDAR
```

**Comment by varac** [comment]
btw, for debugging purposes it would be great to inlcude the todoman version which last created/modified the event. Can the `PRODID` field be used for this ?

**Comment by hobarrera** [comment]
The `VTIMEZONE` is not required because we're not using any timezone our nay of the dates; all datetimes are in UTC (that's what the trailing `Z` means).
